/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to define a custom sidebar
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // Link to docs/intro.md
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'User Guides',
      items: [
        'user-guides/dapp-guide', // Corresponds to docs/user-guides/dapp-guide.md
        // Add more user guides here as needed
      ],
    },
    {
      type: 'category',
      label: 'Developer Documentation',
      items: [
        'developer-docs/overview', // Corresponds to docs/developer-docs/overview.md
        {
          type: 'category',
          label: 'On-Chain Programs',
          items: [
            'developer-docs/on-chain-programs/pool-program',
            'developer-docs/on-chain-programs/oracle-program',
          ],
        },
        {
          type: 'category',
          label: 'Off-Chain Services',
          items: [
            'developer-docs/off-chain-services/pool-maintainer',
            'developer-docs/off-chain-services/oracle-feeder',
          ],
        },
        // {
        //   type: 'category',
        //   label: 'API Reference / IDLs',
        //   items: [], // Placeholder for IDL links/renderings
        // },
      ],
    },
    // Add more top-level categories or docs here
  ],
};

export default sidebars; 